
#the default port of Eureka server is 8761, if you are defining your own port then you need to explicity configure 
#the port in every service
server:
  port: 8761
  
  
#Every Eureka server internally behaves as a eureka client also 
#what if eureka server gets down? by default we have multiple replicas of Eureka server
#so that if main server gets down we will be having others to get our services registered


#this is the property if you don't want your Eureka server to behave as Eureka client
#for other eureka servers.=>do not register it with other Eureka servers
#if your Eureka server behaving as client do not fetch any registry

eureka:
   client:
     fetch-registry: false
     register-with-eureka: false


