
#the default port of Eureka server is 8761, if you are defining your own port then you need to explicity configure 
#the port in every service
server:
  port: 8761
  
  
#Every Eureka server internally behaves as a eureka client also 
#what if eureka server gets down? by default we have multiple replicas of Eureka server
#so that if main server gets down we will be having others to get our services registered

#if you want your eureka server should not get registered with other eureka servers on the same network
#as eureka client so put below properties
eureka:
   client:
     fetch-registry: false
     register-with-eureka: false


